# Generated by Django 4.2.13 on 2024-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('base', models.CharField(default='USD', max_length=3)),
                ('currency', models.TextField(default='EUR', max_length=3)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
    ]
