# Generated by Django 4.2.13 on 2024-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
